function draw_group(ax, xrange, yline, txt, ytxt)
    plot(ax, xrange, [yline yline], 'k', 'LineWidth', 1.2, 'Clipping', 'off');
    text(ax, mean(xrange), ytxt, txt, ...
        'HorizontalAlignment', 'center', ...
        'VerticalAlignment', 'top', ...
        'FontSize', 30, 'Clipping', 'off', ...
        'Interpreter', 'latex', ...    
        'FontName', 'Times New Roman');
end