function conditions = input_condition(meanangle,averageangle)
    Re   = 5e5                       ;%Reynolds number
    st   = 0.19                      ;
    miu  = 1.8e-5                    ;%viscosity
    rho  = 1.225                     ;%density, kg/m3  
    c    = 0.6                         ;%blade chord length, m
    as   = 340.3                     ;%free-stream speed of sound, m/s
    U    = Re*miu/rho/c   ;%free-stream velocity, m/s
    M    = U / as                    ;%Mach number
    beta = sqrt(1 - M^2)             ;%beta parameter
    ff   = 2.4                         ;%pitch oscillation frequency
    k    = pi * ff * c / U           ;%reduced frequency
    w       = 2*pi*ff                ;
    n_T     = 10                     ;
    T       = 2*pi/w*n_T               ;%pitch oscillation period
    n_steps = 5000;
    t       = linspace(0,T,n_steps)     ;%compute one period
    s       = 2 * U * t / c             ;%dimensionless time
    ds      = s(2) - s(1)               ;
    dt      = t(2) - t(1)               ;
    Am      = meanangle                       ;%Mean angle of attack, deg
    A       = averageangle                       ;%pitch oscillation amplitude, deg
    [a,da,q,dq] = get_a_q(Am,A,w,c,U,t);

    conditions.a = a;
    conditions.da = da;
    conditions.q = q;
    conditions.dq = dq;
    conditions.as = as;
    conditions.beta = beta;
    conditions.n_steps = n_steps;
    conditions.ds = ds;
    conditions.dt = dt;
    conditions.U = U;
    conditions.M = M;
    conditions.s = s;
    conditions.t = t;
    conditions.w = w;
    conditions.ff = ff;
    conditions.k = k;
    conditions.Re = Re;
end