function BLPO_make_sample_data()
%BLPO_MAKE_SAMPLE_DATA Generate 2-column and 4-column reference examples.

root = fileparts(mfilename("fullpath"));
addpath(fullfile(root, "functions"));

cfg = BLPO_sample_config();
conditions = BLPO_build_condition( ...
    MeanAngleDeg=cfg.meanAngleDeg, ...
    AmplitudeDeg=cfg.amplitudeDeg, ...
    PhaseDeg=cfg.phaseDeg, ...
    Re=cfg.Re, ...
    Rho=cfg.rho, ...
    Mu=cfg.mu, ...
    Chord=cfg.chord, ...
    SoundSpeed=cfg.soundSpeed, ...
    U=cfg.U, ...
    ReducedFrequency=cfg.reducedFrequency, ...
    FrequencyHz=cfg.frequencyHz, ...
    UseFrequencyHz=cfg.useFrequencyHz, ...
    Cycles=cfg.cycles, ...
    StepsPerCycle=cfg.stepsPerCycle);
airfoil = BLPO_default_airfoil( ...
    PolarFile=string(cfg.polarFile), Chord=cfg.chord, CD0=cfg.CD0, CM0=cfg.CM0, ...
    Alpha1Deg=cfg.alpha1Deg, Alpha2Deg=cfg.alpha2Deg, CN1=cfg.CN1, CN2=cfg.CN2, ...
    Slope=cfg.slope, XAC=cfg.xAC, XCPC=cfg.xcpC);
params = BLPO_default_parameters();

[~, ~, ~, cd, cl, cm] = cal_DS(params.vector, conditions, airfoil);
time = conditions.t(:);
cl = cl(:);
cd = cd(:);
cm = cm(:);

sampleDir = fullfile(root, "sample_data");
if ~isfolder(sampleDir)
    mkdir(sampleDir);
end

idx = (1:4:numel(time))';
noise1 = sin(2 * pi * time(idx) / max(time));
noise2 = cos(2 * pi * time(idx) / max(time));
noise3 = sin(4 * pi * time(idx) / max(time));
experimentData = [time(idx), cl(idx) + 0.015 * noise1];
cfdData = [time(idx), ...
           cl(idx) + 0.010 * noise1, ...
           cd(idx) + 0.003 * noise2, ...
           cm(idx) + 0.002 * noise3];

writematrix(experimentData, fullfile(sampleDir, "sample_reference_experiment_2col.csv"));
writematrix(cfdData, fullfile(sampleDir, "sample_reference_cfd_4col.csv"));
disp("Sample data written to " + string(sampleDir));
end
