function setcase = BLPO_build_setcase(cfg, referenceFile)
%BLPO_BUILD_SETCASE Assemble model condition, airfoil constants and reference data.

arguments
    cfg struct
    referenceFile (1,1) string
end

conditions = BLPO_build_condition( ...
    MeanAngleDeg=cfg.meanAngleDeg, ...
    AmplitudeDeg=cfg.amplitudeDeg, ...
    PhaseDeg=cfg.phaseDeg, ...
    Re=cfg.Re, ...
    Rho=cfg.rho, ...
    Mu=cfg.mu, ...
    Chord=cfg.chord, ...
    SoundSpeed=cfg.soundSpeed, ...
    U=cfg.U, ...
    ReducedFrequency=cfg.reducedFrequency, ...
    FrequencyHz=cfg.frequencyHz, ...
    UseFrequencyHz=cfg.useFrequencyHz, ...
    Cycles=cfg.cycles, ...
    StepsPerCycle=cfg.stepsPerCycle);

airfoildata = BLPO_default_airfoil( ...
    PolarFile=string(cfg.polarFile), ...
    Chord=cfg.chord, ...
    CD0=cfg.CD0, ...
    CM0=cfg.CM0, ...
    Alpha1Deg=cfg.alpha1Deg, ...
    Alpha2Deg=cfg.alpha2Deg, ...
    CN1=cfg.CN1, ...
    CN2=cfg.CN2, ...
    Slope=cfg.slope, ...
    XAC=cfg.xAC, ...
    XCPC=cfg.xcpC);

reference = BLPO_read_reference(referenceFile);

setcase.meanangle = cfg.meanAngleDeg;
setcase.averageangle = cfg.amplitudeDeg;
setcase.conditions = conditions;
setcase.airfoldata = airfoildata;
setcase.CFDdatapath = char(referenceFile);
setcase.reference = reference;
end
