function conditions = input_condition(meanangle,averageangle)
    Re   = 1e6                       ;%雷诺数
    st   = 0.19                      ;
    miu  = 1.8e-5                    ;%粘度
    rho  = 1.225                     ;%密度，kg/m3  
    c    = 1                         ;%叶片弦长，m
    as   = 340.3                     ;%自由流声速，m/s
    U    = 10  ;%Re*miu/rho/c        ;%来流速度，m/s
    M    = U / as                    ;%马赫数
    beta = sqrt(1 - M^2)             ;%参数β
    ff   = 1                         ;%pitch角变化频率
    k    = 0.31  ;%pi*ff*c/U          ;%缩减频率
    w       = 2*k*U/c                ;
    n_T     = 10                     ;
    T       = 2*pi/w*n_T               ;%pitch角变化周期
    n_steps = 5000;
    t       = linspace(0,T,n_steps)     ;%计算一个周期内
    s       = 2 * U * t / c             ;%无量纲时间
    ds      = s(2) - s(1)               ;
    dt      = t(2) - t(1)               ;
    Am      = meanangle                       ;%攻角平均位置，deg
    A       = averageangle                       ;%pitch角变化幅值，deg
    [a,da,q,dq] = get_a_q(Am,-A,w,c,U,t);

    conditions.a = a;
    conditions.da = da;
    conditions.q = q;
    conditions.dq = dq;
    conditions.as = as;
    conditions.beta = beta;
    conditions.n_steps = n_steps;
    conditions.ds = ds;
    conditions.dt = dt;
    conditions.U = U;
    conditions.M = M;
    conditions.s = s;
    conditions.t = t;
    conditions.w = w;
    conditions.ff = ff;
    conditions.k = k;
    conditions.Re = Re;
end